### ISSUE TITLE
Структуирование

### ISSUE THREAD

**Issue by LerinRuss** [Sons-of-Bahcha/rendzy#5]
Предлагаю сначала ПОЛНОСТЬЮ закончить наброски игры. И сделать нормальное СТРУКТУИРОВАНИЕ и самое главное - комментирование классов ( без этого никуда дальше идти вглубь НЕЛЬЗЯ)

**Comment by azeriker** [comment]
Я согласен с тобой, я напишу комменты везде где шарю. Считаю, что наброски игры готовы, основной движок готов, осталось навешивать плюшки
